function Jacob_H = H_matrix_only_attitude(in1)
%H_matrix_only_attitude
%    Jacob_H = H_matrix_only_attitude(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    08-Jun-2025 21:57:12

pitch = in1(2,:);
roll = in1(1,:);
yaw = in1(3,:);
t2 = cos(pitch);
t3 = cos(roll);
t4 = cos(yaw);
t5 = sin(pitch);
t6 = sin(roll);
t7 = sin(yaw);
Jacob_H = reshape([0.0,t2.*t3.*(2.0./5.0)+t6.*t7.*(6.0./2.5e+1)+t3.*t4.*t5.*(6.0./2.5e+1),t2.*t6.*(-2.0./5.0)+t3.*t7.*(6.0./2.5e+1)-t4.*t5.*t6.*(6.0./2.5e+1),0.0,0.0,0.0,t2.*(-2.0./5.0)-t4.*t5.*(6.0./2.5e+1),t5.*t6.*(-2.0./5.0)+t2.*t4.*t6.*(6.0./2.5e+1),t3.*t5.*(-2.0./5.0)+t2.*t3.*t4.*(6.0./2.5e+1),0.0,0.0,0.0,t2.*t7.*(-6.0./2.5e+1),t3.*t4.*(-6.0./2.5e+1)-t5.*t6.*t7.*(6.0./2.5e+1),t4.*t6.*(6.0./2.5e+1)-t3.*t5.*t7.*(6.0./2.5e+1),0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,9]);
end
